---
- name: Install and configure apache ssl mode
  hosts: localhost
  connection: local

  tasks:
  
  - name: Install mod_ssl package
    yum:
      name: mod_ssl
      state: present
    notify: restart httpd

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
